parameters:
  environment:  ''
  targetVersion:  ''
jobs:
  - deployment:  'deploy_aks_${{ parameters.environment }}'
    displayName: 'Deploy AKS in ${{ parameters.environment }}'
    pool:
      vmImage: 'ubuntu-latest'
    environment:  ${{ parameters.environment }}
    variables:
      statefulRg:  'shared-state-${{ parameters.environment }}'
      statelessRgPrefix:  'shared-stateless'
      clusterPrefix:  'cluster'
      dnsPrefix:  'vpl-aks'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            displayName:  Download scripts
            artifact: content
          # Azure CLI:  https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli
          - task: AzureCLI@2
            displayName:  Fetch colour
            inputs:
              azureSubscription: shared-infra
              scriptType:  'bash'
              scriptLocation: 'scriptPath'
              scriptPath:  $(Pipeline.Workspace)/content/fetch-colour.sh
              arguments:  $(statefulRg)
          # Azure CLI:  https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli
          - task: AzureCLI@2
            displayName:  Fetch Log Analytics ID
            inputs:
              azureSubscription: shared-infra
              scriptType:  'bash'
              scriptLocation: 'scriptPath'
              scriptPath:  $(Pipeline.Workspace)/content/fetch-log-analytics-id.sh
              arguments:  $(statefulRg)
          # ARM Deployment:  https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment
          - task: AzureResourceGroupDeployment@2
            inputs:
              azureSubscription: shared-infra
              resourceGroupName: '$(statelessRgPrefix)-$(colour)-${{ parameters.environment }}'
              location: eastus
              templateLocation: 'Linked artifact'
              csmFile: $(Pipeline.Workspace)/content/shared-infra-simple.json
              #csmParametersFile: #Not using it here
              deploymentMode: 'Incremental'
              overrideParameters: -dnsPrefix '$(dnsPrefix)-$(colour)-${{ parameters.environment }}' -logAnalyticsId $(laid) -clusterName '$(clusterPrefix)-$(colour)-${{ parameters.environment }}'
          # Helm tool installer:  https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/helm-installer
          - task: HelmInstaller@1
            inputs:
              helmVersionToInstall: 'latest'