parameters:
  environment:  ''
  targetVersion:  ''
jobs:
  - deployment:  'deploy_aks_${{ parameters.environment }}'
    displayName: 'Deploy AKS in ${{ parameters.environment }}'
    pool:
      vmImage: 'ubuntu-latest'
    environment:  ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            displayName:  Download scripts
            artifact: content
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script:  'pwd'
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script:  'ls -l'
          # ARM Deployment:  https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment
          - task: AzureResourceGroupDeployment@2
            inputs:
              azureSubscription: shared-infra
              resourceGroupName: shared-stateless-${{ parameters.environment }}
              location: eastus
              templateLocation: 'Linked artifact'
              csmFile: $(Pipeline.Workspace)/shared-infra-simple.json
              #csmParametersFile: $(Pipeline.Workspace)/shared-infra-simple.json
              #overrideParameters: # Optional
              deploymentMode: 'Incremental'
