resources:
- repo: self
queue:
  name: Hosted Ubuntu 1604
steps:
# Get Helm
- task: Bash@3
  displayName:  "Get Helm binaries"
  inputs:
    targetType: filePath
    filePath: get-helm.sh

# Copy source to "content" folder
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)/content'
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)/content'

# Publish "content" artefact
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: content'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/content'
    ArtifactName: content
